export const GET_INITIAL_VACANCIES = "GET_INITIAL_VACANCIES";
export const GET_INITIAL_VACANCIES_SUCCESS = "GET_INITIAL_VACANCIES_SUCCESS";
export const GET_INITIAL_VACANCIES_FAIL = "GET_INITIAL_VACANCIES_FAIL";

export const GET_VACANCIES_PAGE = "GET_VACANCIES_PAGE";
export const GET_VACANCIES_PAGE_SUCCESS = "GET_VACANCIES_PAGE";
export const GET_VACANCIES_PAGE_FAIL = "GET_VACANCIES_PAGE_FAIL";
